name: Auto release

permissions:
  contents: write

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - name: Build configs
      run: |
        uv run gen192
    - uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: Development Build
        tag_name: dev
        files: |
          dist/*.zip
